services:
  
  postgres:
    image: postgres:16-alpine
    env_file: .env
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    volumes:
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    network_mode: "host"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4GB"
  
  app1: &app
    build:
      context: ../../app
      dockerfile: Dockerfile
    env_file: .env
    environment:
      APP_PORT: 8001
      DB_HOST: localhost
      DB_PORT: $DATABASE_PORT
      DB_USER: $DATABASE_USER
      DB_PASSWORD: $DATABASE_PASSWORD
      DB_NAME: $DATABASE_NAME
    network_mode: "host"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1GB"
    depends_on:
      postgres:
        condition: service_healthy
  
  app2:
    <<: *app
    environment:
      APP_PORT: 8002
      DB_HOST: localhost
      DB_PORT: $DATABASE_PORT
      DB_USER: $DATABASE_USER
      DB_PASSWORD: $DATABASE_PASSWORD
      DB_NAME: $DATABASE_NAME

  app3:
    <<: *app
    environment:
      APP_PORT: 8003
      DB_HOST: localhost
      DB_PORT: $DATABASE_PORT
      DB_USER: $DATABASE_USER
      DB_PASSWORD: $DATABASE_PASSWORD
      DB_NAME: $DATABASE_NAME

  app4:
    <<: *app
    environment:
      APP_PORT: 8004
      DB_HOST: localhost
      DB_PORT: $DATABASE_PORT
      DB_USER: $DATABASE_USER
      DB_PASSWORD: $DATABASE_PASSWORD
      DB_NAME: $DATABASE_NAME

  app5:
    <<: *app
    environment:
      APP_PORT: 8005
      DB_HOST: localhost
      DB_PORT: $DATABASE_PORT
      DB_USER: $DATABASE_USER
      DB_PASSWORD: $DATABASE_PASSWORD
      DB_NAME: $DATABASE_NAME

  app6:
    <<: *app
    environment:
      APP_PORT: 8006
      DB_HOST: localhost
      DB_PORT: $DATABASE_PORT
      DB_USER: $DATABASE_USER
      DB_PASSWORD: $DATABASE_PASSWORD
      DB_NAME: $DATABASE_NAME

  app7:
    <<: *app
    environment:
      APP_PORT: 8007
      DB_HOST: localhost
      DB_PORT: $DATABASE_PORT
      DB_USER: $DATABASE_USER
      DB_PASSWORD: $DATABASE_PASSWORD
      DB_NAME: $DATABASE_NAME

  app8:
    <<: *app
    environment:
      APP_PORT: 8008
      DB_HOST: localhost
      DB_PORT: $DATABASE_PORT
      DB_USER: $DATABASE_USER
      DB_PASSWORD: $DATABASE_PASSWORD
      DB_NAME: $DATABASE_NAME

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4GB"
    depends_on:
      - app1
      - app2
  
